# Simple Dockerfile using pre-built JAR
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
EXPOSE 8082
ENV JAVA_OPTS=""
COPY target/*.jar /app/app.jar
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar"]
