resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 2000
    instances:
      warehouseService:
        baseConfig: default
      shopService:
        baseConfig: default
  
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      warehouseService:
        baseConfig: default
      shopService:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
    instances:
      apiRateLimit:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      warehouseService:
        baseConfig: default
      shopService:
        baseConfig: default
