INSERT IGNORE INTO reviews (product_id, user_id, rating, content, status, is_verified_purchase, created_at, updated_at) VALUES
(1, 26, 5, 'Sản phẩm tuyệt vời, thiết kế rất sang trọng!', 'APPROVED', 1, NOW(), NOW()),
(1, 27, 4, 'Máy đẹp, hơi đắt nhưng đáng đồng tiền bát gạo.', 'APPROVED', 1, NOW(), NOW()),
(1, 28, 5, 'Màu Titan Tự Nhiên cực kỳ đẹp, nhân viên giao hàng nhiệt tình.', 'APPROVED', 1, NOW(), NOW()),
(2, 26, 4, 'iPhone 14 Plus màn hình to xem phim sướng, pin trâu.', 'APPROVED', 1, NOW(), NOW()),
(3, 26, 5, 'Samsung S24 Ultra zoom cực đỉnh, AI rất thông minh.', 'APPROVED', 1, NOW(), NOW()),
(3, 27, 5, 'Trải nghiệm mượt mà, bút S-Pen rất tiện lợi cho công việc.', 'APPROVED', 1, NOW(), NOW()),
(4, 28, 5, 'Tivi Sony màu sắc trung thực, âm thanh vòm nghe rất hay.', 'APPROVED', 1, NOW(), NOW()),
(5, 29, 4, 'Dell XPS 15 mỏng nhẹ, hiệu năng mạnh mẽ cân mọi tác vụ đồ họa.', 'APPROVED', 1, NOW(), NOW()),
(6, 30, 5, 'Chống ồn của Sony XM5 thực sự là số 1 hiện nay.', 'APPROVED', 1, NOW(), NOW()),
(7, 31, 5, 'Macbook Air M2 quá nhẹ, pin dùng cả ngày không cần sạc.', 'APPROVED', 1, NOW(), NOW()),
(8, 32, 5, 'Camera Leica của Xiaomi 14 Ultra đỉnh cao nhiếp ảnh.', 'APPROVED', 1, NOW(), NOW()),
(9, 33, 4, 'Chuột MX Master 3S dùng rất êm, nút cuộn magspeed cực thích.', 'APPROVED', 1, NOW(), NOW()),
(10, 34, 5, 'Máy PS5 Slim thiết kế đẹp, chơi game 4K mượt mà.', 'APPROVED', 1, NOW(), NOW()),
(11, 35, 5, 'Hàng chính hãng Tiki Trading nên rất yên tâm.', 'APPROVED', 1, NOW(), NOW()),
(12, 36, 3, 'Máy thỉnh thoảng hơi nóng khi chơi game nặng lâu.', 'APPROVED', 1, NOW(), NOW()),
(13, 26, 5, 'Canon R6 Mark II lấy nét siêu nhanh, chất lượng ảnh tuyệt vời.', 'APPROVED', 1, NOW(), NOW()),
(14, 27, 4, 'Laptop Legion 5 Pro tản nhiệt tốt, màn hình 2K sắc nét.', 'APPROVED', 1, NOW(), NOW()),
(15, 28, 5, 'iPad Pro M2 xử lý video 4K cực nhanh.', 'APPROVED', 1, NOW(), NOW()),
(16, 29, 5, 'ASUS ROG Strix G16 cấu hình cực mạnh, led RGB rất đẹp.', 'APPROVED', 1, NOW(), NOW()),
(17, 30, 4, 'Apple Watch Ultra 2 pin trâu hơn hẳn các đời trước.', 'APPROVED', 1, NOW(), NOW()),
(18, 31, 5, 'Samsung A54 dùng ổn định, camera đẹp trong tầm giá.', 'APPROVED', 1, NOW(), NOW()),
(19, 32, 4, 'Tủ lạnh LG Side by side rất rộng rãi, làm lạnh nhanh.', 'APPROVED', 1, NOW(), NOW()),
(20, 33, 5, 'Oppo Find X7 Ultra thiết kế lạ mắt, camera Hasselblad đỉnh.', 'APPROVED', 1, NOW(), NOW()),
(21, 34, 5, 'Máy giặt Panasonic giặt sạch, máy chạy êm.', 'APPROVED', 1, NOW(), NOW()),
(22, 35, 4, 'HP Pavilion 15 văn phòng ổn, vỏ nhôm sang trọng.', 'APPROVED', 1, NOW(), NOW()),
(23, 36, 5, 'Chuột Razer DeathAdder V3 nhẹ kinh ngạc.', 'APPROVED', 1, NOW(), NOW()),
(24, 26, 5, 'RAM Corsair lắp vào máy nhận ngay, led đẹp.', 'APPROVED', 1, NOW(), NOW()),
(25, 27, 5, 'SSD WD Black SN850X tốc độ copy file siêu nhanh.', 'APPROVED', 1, NOW(), NOW()),
(1, 28, 4, 'Samsung Watch 6 Classic vòng xoay bezel rất tiện.', 'APPROVED', 1, NOW(), NOW()),
(2, 29, 4, 'Laptop MSI Cyborg thiết kế lạ, chơi game tốt.', 'APPROVED', 1, NOW(), NOW());
