-- Seed 26 notifications for users
INSERT IGNORE INTO notifications (user_id, title, message, type, is_read, created_at) VALUES
(26, 'Đơn hàng mới', 'Đơn hàng ORD-1710000000021 của bạn đã được thanh toán thành công.', 'ORDER_STATUS', 0, NOW()),
(27, 'Đã giao hàng', 'Đơn hàng ORD-1710000000022 đã được giao thành công. Đánh giá ngay!', 'ORDER_STATUS', 1, NOW()),
(28, 'Khuyến mãi cực hot', 'Giảm ngay 50% cho các dòng iPhone 15 trong hôm nay.', 'PROMOTION', 0, NOW()),
(26, 'Thông báo hệ thống', 'Chào mừng bạn đến với Tiki Clone. Chúc bạn mua sắm vui vẻ!', 'SYSTEM', 1, NOW()),
(29, 'Đơn hàng đang giao', 'Đơn hàng ORD-1710000000004 đang trên đường đến với bạn.', 'ORDER_STATUS', 0, NOW()),
(30, 'Chào bạn mới', 'Tặng bạn voucher 50k cho đơn hàng đầu tiên từ 200k.', 'PROMOTION', 0, NOW()),
(31, 'Đơn hàng đã hủy', 'Đơn hàng ORD-1710000000007 của bạn đã bị hủy.', 'ORDER_STATUS', 1, NOW()),
(32, 'Xác nhận đơn hàng', 'Đơn hàng của bạn đã được xác nhận bởi người bán.', 'ORDER_STATUS', 0, NOW()),
(33, 'Ưu đãi dành riêng cho bạn', 'Giảm 100k cho đơn hàng Samsung trên 5 triệu.', 'PROMOTION', 0, NOW()),
(34, 'Cập nhật tài khoản', 'Mật khẩu của bạn đã được thay đổi thành công.', 'SYSTEM', 1, NOW()),
(35, 'Đơn hàng đang chuẩn bị', 'Đơn hàng của bạn đang được người bán đóng gói.', 'ORDER_STATUS', 0, NOW()),
(36, 'Hàng đã về', 'Sản phẩm bạn yêu thích đã có hàng lại. Mua ngay!', 'PROMOTION', 0, NOW()),
(37, 'Nhắc nhở thanh toán', 'Vui lòng hoàn tất thanh toán cho đơn hàng ORD-1710000000010.', 'ORDER_STATUS', 0, NOW()),
(38, 'Mã giảm giá sắp hết hạn', 'Voucher 10% của bạn sẽ hết hạn sau 2 giờ nữa.', 'PROMOTION', 0, NOW()),
(26, 'Sản phẩm mới', 'Macbook M3 đã ra mắt. Xem ngay cấu hình khủng!', 'PROMOTION', 0, NOW()),
(27, 'Đánh giá sản phẩm', 'Bạn thấy iPhone 14 Plus thế nào? Chia sẻ cảm nhận nhé.', 'SYSTEM', 0, NOW()),
(28, 'Hoàn tiền thành công', 'Yêu cầu hoàn tiền cho đơn hàng ORD-1710000000020 đã được xử lý.', 'ORDER_STATUS', 1, NOW()),
(29, 'Bảo mật tài khoản', 'Phát hiện đăng nhập lạ từ thiết bị mới.', 'SYSTEM', 0, NOW()),
(30, 'Tin nhắn từ người bán', 'Shop Sony Center đã trả lời câu hỏi của bạn.', 'MESSAGE', 0, NOW()),
(31, 'Giỏ hàng đang chờ', 'Bạn vẫn còn 3 sản phẩm trong giỏ hàng. Chốt đơn ngay!', 'SYSTEM', 0, NOW()),
(32, 'Thành viên mới', 'Bạn đã đạt mức hạng Bạc. Nhận thêm nhiều ưu đãi!', 'SYSTEM', 0, NOW()),
(33, 'Flash Sale', 'Samsung Galaxy S24 Ultra đang giảm sốc chỉ trong 2 giờ.', 'PROMOTION', 0, NOW()),
(34, 'Đơn hàng bị trả lại', 'Đơn hàng bị trả lại do không liên lạc được với người nhận.', 'ORDER_STATUS', 0, NOW()),
(35, 'Cảm ơn bạn', 'Cảm ơn bạn đã mua sắm tại Tiki. Hẹn gặp lại!', 'SYSTEM', 1, NOW()),
(36, 'Nhận quà 0đ', 'Cơ hội nhận quà 0đ mỗi ngày. Tham gia ngay!', 'PROMOTION', 0, NOW()),
(26, 'Đơn hàng sắp đến', 'Shipper đang ở gần khu vực của bạn.', 'ORDER_STATUS', 0, NOW());
