-- Seed shops linked to SELLER users (IDs 2-25)
INSERT IGNORE INTO shops (id, seller_id, shop_name, description, logo_url, status, created_at) VALUES
(1, 2, 'Apple Flagship Store', 'Cửa hàng chính thức của Apple tại Việt Nam', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg', 'ACTIVE', NOW()),
(2, 3, 'Samsung Official Store', 'Trải nghiệm công nghệ đỉnh cao từ Samsung', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg', 'ACTIVE', NOW()),
(3, 4, 'Sony Center', 'Nghệ thuật âm thanh và hình ảnh', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg', 'ACTIVE', NOW()),
(4, 5, 'Dell Official', 'Máy tính xách tay và thiết bị IT hàng đầu', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg', 'ACTIVE', NOW()),
(5, 6, 'Xiaomi Global', 'Công nghệ cho mọi người', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Xiaomi_logo_%282021-%29.svg', 'ACTIVE', NOW()),
(6, 7, 'Oppo Vietnam', 'Chuyên gia selfie', 'https://upload.wikimedia.org/wikipedia/commons/0/09/Oppo_logo_2019.svg', 'ACTIVE', NOW()),
(7, 8, 'Sony VN', 'Phân phối chính hãng Sony', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg', 'ACTIVE', NOW()),
(8, 9, 'Panasonic Store', 'Giải pháp gia dụng thông minh', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Panasonic_logo.svg', 'ACTIVE', NOW()),
(9, 10, 'LG Global', 'Life is Good', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/LG_logo_%282015%29.svg', 'ACTIVE', NOW()),
(10, 11, 'Toshiba Vietnam', 'Đến từ Nhật Bản', 'https://upload.wikimedia.org/wikipedia/commons/4/43/Toshiba_logo.svg', 'ACTIVE', NOW()),
(11, 12, 'HP Official', 'Sáng tạo không giới hạn', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/HP_logo_2012.svg', 'ACTIVE', NOW()),
(12, 13, 'Asus Vietnam', 'In Search of Incredible', 'https://upload.wikimedia.org/wikipedia/commons/d/de/Asus-logo.svg', 'ACTIVE', NOW()),
(13, 14, 'Acer Flagship', 'Khám phá thế giới', 'https://upload.wikimedia.org/wikipedia/commons/8/82/Acer_logo.svg', 'ACTIVE', NOW()),
(14, 15, 'Lenovo Store', 'Smarter technology for all', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Lenovo_logo_2015.svg', 'ACTIVE', NOW()),
(15, 16, 'MSI Gaming Hub', 'True Gaming', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/MSI_logo.svg', 'ACTIVE', NOW()),
(16, 17, 'Logitech VN', 'Sáng tạo và chính xác', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Logitech_logo.svg', 'ACTIVE', NOW()),
(17, 18, 'Razer Zone', 'For Gamers. By Gamers.', 'https://upload.wikimedia.org/wikipedia/commons/4/40/Razer_Snake_Logo.svg', 'ACTIVE', NOW()),
(18, 19, 'Corsair Official', 'Thiết bị PC cao cấp', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Corsair_Components_Logo.svg', 'ACTIVE', NOW()),
(19, 20, 'Kingston VN', 'Bộ nhớ và lưu trữ hàng đầu', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Kingston_Technology_logo.svg', 'ACTIVE', NOW()),
(20, 21, 'WD Official', 'Dẫn đầu về lưu trữ', 'https://upload.wikimedia.org/wikipedia/commons/7/77/Western_Digital_logo.svg', 'ACTIVE', NOW()),
(21, 22, 'Seagate Store', 'Lưu trữ an toàn', 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Seagate_logo.svg', 'ACTIVE', NOW()),
(22, 23, 'TP-Link Vietnam', 'Kết nối thông minh', 'https://upload.wikimedia.org/wikipedia/commons/6/6d/TP-Link_logo.svg', 'ACTIVE', NOW()),
(23, 24, 'Linksys Official', 'Giải pháp mạng gia đình', 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Linksys_logo.svg', 'ACTIVE', NOW()),
(24, 25, 'D-Link VN', 'Building Networks for People', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/D-Link_logo.svg', 'ACTIVE', NOW());
